import fs from 'node:fs'

const u = (s) => s // keep as-is; file is UTF-8 source

const lines = []
const L = (s) => lines.push(s)

L("import { Link } from 'react-router-dom'")
L("import { ArrowRight, Flag, FlaskConical, Shield, Swords } from 'lucide-react'")
L("import { getStage } from '@/mocks/data'")
L("import { formatDateJa, seriesProgressLabel } from '@/mocks/schedule'")
L("import { useAppState } from '@/context/AppState'")
L("import { Badge } from '@/components/ui/badge'")
L("import { Button } from '@/components/ui/button'")
L("import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'")
L("import { Progress } from '@/components/ui/progress'")
L("import { Separator } from '@/components/ui/separator'")
L('')
L('export function HomeMap() {')
L('  const { currentStudent, todayQueue, mockToday, setMockToday, stages } = useAppState()')
L('  if (!currentStudent || !todayQueue) return null')
L('')
L('  const p = currentStudent.progress')
L('  const reqTotal = stages.filter((s) => s.required).length')
L('  const reqDone = p.clearedStageIds.filter((id) => getStage(id)?.required).length')
L('  const pct = reqTotal ? Math.round((reqDone / reqTotal) * 100) : 0')
L('  const visitIndex =')
L('    currentStudent.visitDates.indexOf(mockToday) >= 0')
L('      ? currentStudent.visitDates.indexOf(mockToday) + 1')
L('      : null')
L('')
L('  return (')
L('    <div className="space-y-5">')
L('      <Card className="overflow-hidden border-primary/25 bg-gradient-to-br from-card via-card to-teal-950/40">')
L('        <CardContent className="flex flex-wrap items-center justify-between gap-4 p-5">')
L('          <div>')
L('            <div className="mb-1 flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-primary">')
L('              <Swords className="h-3.5 w-3.5" />')
L("              Today&apos;s Quest")
L('            </div>')
L('            <h2 className="font-display text-2xl text-emerald-50">')
L('              {formatDateJa(mockToday)}')
L('              {visitIndex ? ` \\u00b7 \\u6765\\u9662 ${visitIndex} \\u65e5\\u76ee` : \"\"}')
L('            </h2>')
L('            <p className="mt-1 text-sm text-muted-foreground">')
L('              {todayQueue.plan.note ||')
L('                (todayQueue.isAppOffDay')
L("                  ? '\\u672c\\u65e5\\u306f\\u30a2\\u30d7\\u30ea\\u5b66\\u7fd2\\u306a\\u3057\\uff08\\u898b\\u5b66\\u306a\\u3069\\uff09'")
L("                  : '\\u8a08\\u753b\\u30b7\\u30ea\\u30fc\\u30ba\\u3068\\u7e70\\u308a\\u8d8a\\u3057\\u3092\\u6d88\\u5316\\u3057\\u3088\\u3046')}")
L('            </p>')
L('          </div>')
L('          <div className="flex flex-wrap gap-2">')
L('            {sortUnique(currentStudent.visitDates).map((d) => (')
L('              <Button')
L('                key={d}')
L('                size="sm"')
L("                variant={d === mockToday ? 'default' : 'outline'}")
L('                onClick={() => setMockToday(d)}')
L('              >')
L('                {formatDateJa(d)}')
L('              </Button>')
L('            ))}')
L('          </div>')
L('        </CardContent>')
L('      </Card>')
L('')
L('      {todayQueue.carryIds.length > 0 && (')
L('        <div className="flex items-start gap-3 rounded-xl border border-amber-500/40 bg-amber-950/40 px-4 py-3 text-amber-100">')
L('          <Flag className="mt-0.5 h-5 w-5 shrink-0" />')
L('          <div>')
L("            <div className=\"font-medium\">\\u7e70\\u308a\\u8d8a\\u3057\\u30af\\u30a8\\u30b9\\u30c8\\u767a\\u751f</div>")
L('            <div className="text-sm opacity-90">')
L("              {todayQueue.carryIds.map((id) => getStage(id)?.title).join('\\u3001')}")
L('              \\u3092\\u5148\\u306b\\u30af\\u30ea\\u30a2\\u3057\\u3066\\u304b\\u3089\\u3001\\u672c\\u65e5\\u8a08\\u753b\\u3078\\u9032\\u307f\\u307e\\u3059\\u3002')
L('            </div>')
L('          </div>')
L('        </div>')
L('      )}')
L('')
L('      {todayQueue.isAppOffDay && (')
L('        <div className="rounded-xl border border-orange-400/40 bg-orange-950/30 px-4 py-3 text-orange-100">')
L('          \\u672c\\u65e5\\u306f\\u30b7\\u30ea\\u30fc\\u30ba\\u5272\\u5f53\\u306a\\u3057\\u3002\\u73fe\\u5834\\u898b\\u5b66\\u30fb\\u5b9f\\u7fd2\\u306e\\u65e5\\u3067\\u3059\\u3002')
L('        </div>')
L('      )}')
L('')
L('      <div className="grid gap-5 lg:grid-cols-[1.35fr_0.85fr]">')
L('        <Card className="border-primary/20">')
L('          <CardHeader>')
L('            <CardTitle className="flex items-center gap-2 text-emerald-50">')
L('              <FlaskConical className="h-5 w-5 text-primary" />')
L('              \\u5192\\u967a\\u30de\\u30c3\\u30d7 \\u00b7 \\u4eca\\u65e5\\u306e\\u30b7\\u30ea\\u30fc\\u30ba')
L('            </CardTitle>')
L('            <CardDescription>')
L('              \\u8a08\\u753b {todayQueue.plan.seriesIds.length} \\u672c')
L("              {todayQueue.carryIds.length > 0 ? ` \\uff0b \\u7e70\\u308a\\u8d8a\\u3057 ${todayQueue.carryIds.length}` : ''}")
L('            </CardDescription>')
L('          </CardHeader>')
L('          <CardContent className="space-y-3">')
L('            {todayQueue.queueIds.length === 0 && todayQueue.isVisitDay && !todayQueue.isAppOffDay && (')
L('              <div className="rounded-lg border border-emerald-500/30 bg-emerald-950/40 px-4 py-3 text-emerald-100">')
L('                \\u672c\\u65e5\\u5206\\u30af\\u30ea\\u30a2\\uff01\\u30b9\\u30bf\\u30f3\\u30d7\\u7372\\u5f97\\u6e08\\u307f\\u3067\\u3059\\u3002')
L('              </div>')
L('            )}')
L('')
L('            {todayQueue.queueIds.map((id, i) => {')
L('              const stage = getStage(id)')
L('              const carried = todayQueue.carryIds.includes(id)')
L('              return (')
L("                <Link key={id} to={`/app/stage/${id}`} className={`map-node ${carried ? 'carry' : ''}`}>")
L('                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-primary/40 bg-primary/20 font-display text-lg text-primary">')
L('                    {i + 1}')
L('                  </div>')
L('                  <div className="min-w-0 flex-1">')
L('                    <div className="font-medium text-emerald-50">{stage?.title ?? id}</div>')
L('                    <div className="mt-1 flex flex-wrap gap-1.5">')
L("                      {carried ? <Badge variant=\"quest\">\\u7e70\\u308a\\u8d8a\\u3057</Badge> : <Badge variant=\"ok\">\\u672c\\u65e5\\u8a08\\u753b</Badge>}")
L("                      {stage?.hasProcedure && <Badge variant=\"secondary\">\\u624b\\u6280\\u30c1\\u30a7\\u30c3\\u30af</Badge>}")
L('                      <Badge variant="outline">{seriesProgressLabel(currentStudent, id)}</Badge>')
L('                    </div>')
L('                  </div>')
L('                  <ArrowRight className="h-4 w-4 text-muted-foreground" />')
L('                </Link>')
L('              )')
L('            })}')
L('')
L('            {todayQueue.plan.seriesIds')
L('              .filter((id) => p.clearedStageIds.includes(id))')
L('              .map((id) => (')
L('                <Link key={`done-${id}`} to={`/app/stage/${id}`} className="map-node done">')
L('                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-600/30 text-emerald-300">')
L('                    OK')
L('                  </div>')
L('                  <div className="flex-1">')
L('                    <div className="font-medium">{getStage(id)?.title}</div>')
L('                    <Badge variant="ok" className="mt-1">')
L('                      \\u30af\\u30ea\\u30a2\\u6e08')
L('                    </Badge>')
L('                  </div>')
L('                </Link>')
L('              ))}')
L('          </CardContent>')
L('        </Card>')
L('')
L('        <div className="space-y-5">')
L('          <Card>')
L('            <CardHeader>')
L('              <CardTitle className="text-lg text-emerald-50">\\u5192\\u967a\\u306e\\u9032\\u6367</CardTitle>')
L('            </CardHeader>')
L('            <CardContent className="space-y-4">')
L('              <div>')
L('                <div className="mb-2 flex justify-between text-sm">')
L('                  <span className="text-muted-foreground">\\u5fc5\\u9808\\u30b7\\u30ea\\u30fc\\u30ba</span>')
L('                  <span>')
L('                    {reqDone} / {reqTotal}')
L('                  </span>')
L('                </div>')
L('                <Progress value={pct} />')
L('              </div>')
L('              <Separator />')
L('              <div className="grid grid-cols-2 gap-3 text-center">')
L('                <div className="rounded-lg border border-border bg-secondary/40 p-3">')
L('                  <div className="text-xs text-muted-foreground">XP</div>')
L('                  <div className="font-display text-2xl text-amber-200">{p.xp}</div>')
L('                </div>')
L('                <div className="rounded-lg border border-border bg-secondary/40 p-3">')
L('                  <div className="text-xs text-muted-foreground">\\u30b9\\u30bf\\u30f3\\u30d7</div>')
L('                  <div className="font-display text-2xl text-amber-200">{p.stamps}</div>')
L('                </div>')
L('              </div>')
L('              {(todayQueue.isFinalVisit || p.clearedStageIds.length > 0) && (')
L('                <div className="space-y-2 pt-1">')
L('                  {p.cbtSubmitted && !p.cbtRetakeAllowed ? (')
L('                    <Button asChild variant="secondary" className="w-full">')
L('                      <Link to="/app/cbt/result">\\u30dc\\u30b9\\u6226\\u7d50\\u679c\\u3092\\u898b\\u308b</Link>')
L('                    </Button>')
L('                  ) : (')
L('                    <Button asChild variant="quest" className="w-full">')
L('                      <Link to="/app/cbt">\\u6700\\u7d42\\u78ba\\u8a8d\\u30c6\\u30b9\\u30c8\\uff08\\u30dc\\u30b9\\u6226\\uff09</Link>')
L('                    </Button>')
L('                  )}')
L('                  <p className="text-xs text-muted-foreground">')
L('                    \\u30af\\u30ea\\u30a2\\u6e08\\u307f\\u30b7\\u30ea\\u30fc\\u30ba\\u306e\\u554f\\u984c\\u3060\\u3051\\u3067\\u69cb\\u6210\\u3002\\u5408\\u5426\\u306a\\u3057\\u30fb\\u7d20\\u70b9\\u306e\\u307f\\u3002')
L('                  </p>')
L('                </div>')
L('              )}')
L('            </CardContent>')
L('          </Card>')
L('')
L('          <Card>')
L('            <CardHeader>')
L('              <CardTitle className="flex items-center gap-2 text-lg text-emerald-50">')
L('                <Shield className="h-4 w-4 text-primary" />')
L('                \\u6765\\u9662\\u30ab\\u30ec\\u30f3\\u30c0\\u30fc')
L('              </CardTitle>')
L('            </CardHeader>')
L('            <CardContent>')
L('              <ul className="space-y-2 text-sm text-muted-foreground">')
L('                {currentStudent.dayPlans.map((plan) => (')
L('                  <li key={plan.date} className="flex gap-2 border-b border-border/50 pb-2 last:border-0">')
L('                    <span className="w-24 shrink-0 text-foreground">{formatDateJa(plan.date)}</span>')
L('                    <span>')
L('                      {plan.seriesIds.length === 0')
L("                        ? plan.note || '\\u30a2\\u30d7\\u30ea\\u306a\\u3057'")
L("                        : plan.seriesIds.map((id) => getStage(id)?.title).join('\\u3001')}")
L('                    </span>')
L('                  </li>')
L('                ))}')
L('              </ul>')
L('            </CardContent>')
L('          </Card>')
L('        </div>')
L('      </div>')
L('    </div>')
L('  )')
L('}')
L('')
L('function sortUnique(dates: string[]) {')
L('  return [...dates].sort()')
L('}')
L('')

// Convert literal \uXXXX sequences in the generated source into real Unicode
const raw = lines.join('\n')
const decoded = raw.replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
fs.writeFileSync('src/pages/HomeMap.tsx', decoded, 'utf8')
const buf = fs.readFileSync('src/pages/HomeMap.tsx')
new TextDecoder('utf-8', { fatal: true }).decode(buf)
console.log('HomeMap.tsx OK', buf.length)
