import fs from 'node:fs'

const lines = []
const L = (s) => lines.push(s)

L("import { useState, type FormEvent } from 'react'")
L("import { Link, Navigate, useNavigate } from 'react-router-dom'")
L("import { Compass, Map } from 'lucide-react'")
L("import { useAppState } from '@/context/AppState'")
L("import { Button } from '@/components/ui/button'")
L("import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'")
L("import { Input } from '@/components/ui/input'")
L("import { Label } from '@/components/ui/label'")
L('')
L('export function StudentLogin() {')
L('  const { loginStudent, currentStudent } = useAppState()')
L('  const navigate = useNavigate()')
L("  const [code, setCode] = useState('TRAIN01')")
L("  const [password, setPassword] = useState('1234')")
L('  const [error, setError] = useState<string | null>(null)')
L('')
L('  if (currentStudent) return <Navigate to="/app" replace />')
L('')
L('  function onSubmit(e: FormEvent) {')
L('    e.preventDefault()')
L('    const err = loginStudent(code, password)')
L('    if (err) setError(err)')
L("    else navigate('/app')")
L('  }')
L('')
L('  return (')
L('    <div className="flex min-h-screen items-center justify-center px-6 py-10">')
L('      <Card className="w-full max-w-md quest-glow border-primary/30">')
L('        <CardHeader className="space-y-3">')
L('          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/20 text-primary">')
L('            <Compass className="h-6 w-6" />')
L('          </div>')
L('          <CardTitle className="text-3xl text-emerald-50">\\u751f\\u5316\\u5b66\\u514d\\u75ab\\u30e9\\u30dc\\u30af\\u30a8\\u30b9\\u30c8</CardTitle>')
L('          <CardDescription className="text-base text-muted-foreground">')
L('            \\u81e8\\u5730\\u5b9f\\u7fd2\\u306e\\u5192\\u967a\\u30af\\u30a8\\u30b9\\u30c8\\u3002\\u5fd9\\u3057\\u3044\\u6307\\u5c0e\\u306e\\u3042\\u3044\\u3060\\u3082\\u3001\\u81e8\\u5e8a\\u306e\\u5b66\\u3073\\u3092\\u9032\\u3081\\u307e\\u3059\\u3002')
L('          </CardDescription>')
L('        </CardHeader>')
L('        <CardContent>')
L('          <form className="space-y-4" onSubmit={onSubmit}>')
L('            <div className="space-y-2">')
L('              <Label htmlFor="code">\\u53d7\\u8b1b\\u30b3\\u30fc\\u30c9</Label>')
L('              <Input id="code" value={code} onChange={(e) => setCode(e.target.value)} />')
L('            </div>')
L('            <div className="space-y-2">')
L('              <Label htmlFor="password">\\u30d1\\u30b9\\u30ef\\u30fc\\u30c9</Label>')
L('              <Input')
L('                id="password"')
L('                type="password"')
L('                value={password}')
L('                onChange={(e) => setPassword(e.target.value)}')
L('              />')
L('            </div>')
L('            {error && <p className="text-sm text-destructive">{error}</p>}')
L('            <Button type="submit" className="w-full" size="lg">')
L('              <Map className="h-4 w-4" />')
L('              \\u5192\\u967a\\u3092\\u59cb\\u3081\\u308b')
L('            </Button>')
L('          </form>')
L('          <p className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">')
L('            \\u30e2\\u30c3\\u30af: TRAIN01 / 1234\\uff08\\u5c71\\u7530\\uff09\\u30fbTRAIN02 / 5678\\uff08\\u4f50\\u85e4\\uff09')
L('            <br />')
L('            <Link className="text-primary underline-offset-2 hover:underline" to="/staff/login">')
L('              \\u30b9\\u30bf\\u30c3\\u30d5\\u30ed\\u30b0\\u30a4\\u30f3\\u3078')
L('            </Link>')
L('          </p>')
L('        </CardContent>')
L('      </Card>')
L('    </div>')
L('  )')
L('}')
L('')
L('export function StaffLogin() {')
L('  const { loginStaff, currentStaff } = useAppState()')
L('  const navigate = useNavigate()')
L("  const [password, setPassword] = useState('ops')")
L('  const [error, setError] = useState<string | null>(null)')
L('')
L('  if (currentStaff) return <Navigate to="/staff/progress" replace />')
L('')
L('  function onSubmit(e: FormEvent) {')
L('    e.preventDefault()')
L('    const err = loginStaff(password)')
L('    if (err) setError(err)')
L("    else navigate('/staff/progress')")
L('  }')
L('')
L('  return (')
L('    <div className="surface-light flex min-h-screen items-center justify-center px-6">')
L('      <Card className="w-full max-w-md border-teal-200 bg-white">')
L('        <CardHeader>')
L('          <CardTitle className="text-2xl text-teal-900">\\u7ba1\\u7406\\u30ed\\u30b0\\u30a4\\u30f3</CardTitle>')
L('          <CardDescription>\\u9032\\u6367\\u30fb\\u30ab\\u30ec\\u30f3\\u30c0\\u30fc\\u5272\\u5f53\\u30fb\\u516c\\u958b\\u7ba1\\u7406</CardDescription>')
L('        </CardHeader>')
L('        <CardContent>')
L('          <form className="space-y-4" onSubmit={onSubmit}>')
L('            <div className="space-y-2">')
L('              <Label htmlFor="pw">\\u30d1\\u30b9\\u30ef\\u30fc\\u30c9\\uff08\\u30e2\\u30c3\\u30af\\uff09</Label>')
L('              <Input')
L('                id="pw"')
L('                type="password"')
L('                value={password}')
L('                onChange={(e) => setPassword(e.target.value)}')
L('              />')
L('            </div>')
L('            {error && <p className="text-sm text-destructive">{error}</p>}')
L('            <Button type="submit" className="w-full">')
L('              \\u5165\\u5ba4')
L('            </Button>')
L('          </form>')
L('          <p className="mt-4 text-xs text-muted-foreground">')
L('            \\u30d5\\u30eb: <code>full</code> \\uff0f \\u904b\\u7528: <code>ops</code>')
L('            <br />')
L('            <Link className="text-teal-700 underline" to="/">')
L('              \\u5b9f\\u7fd2\\u751f\\u30ed\\u30b0\\u30a4\\u30f3\\u3078')
L('            </Link>')
L('          </p>')
L('        </CardContent>')
L('      </Card>')
L('    </div>')
L('  )')
L('}')
L('')

const raw = lines.join('\n')
const decoded = raw.replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
fs.writeFileSync('src/pages/Login.tsx', decoded, 'utf8')
new TextDecoder('utf-8', { fatal: true }).decode(fs.readFileSync('src/pages/Login.tsx'))
console.log('Login.tsx restored', decoded.includes('生化学免疫ラボクエスト'))
