// src/pages/Admin.tsx から移動(Phase 4)。ProgressDashboard/StudentAdmin/
// ContentAdmin/CbtResultsAdmin/コンテンツエディタで共有する文言。
export const JP = {
  progressTitle: '進捗一覧',
  progressDesc:
    'モック今日: {date}。必須残・繰り越し・CBT素点を確認。合否は表示しません。',
  name: '氏名',
  visitDays: '実習日数',
  requiredClear: '必須クリア',
  requiredRemain: '必須残',
  todayQueue: '今日キュー',
  carryover: '繰り越し',
  cbtScore: 'CBT素点',
  comma: '、',
  dash: '—',
  notTaken: '未受験',
  saveNeedNameDates: '氏名と実習日（1日以上）が必須です',
  missingRequiredPrefix: '必須シリーズ未割当: ',
  saveConfirm: 'このまま保存しますか？',
  savedMock: '保存しました（モック）',
  studentAdminTitle: '実習生登録・カレンダー割当',
  newRegister: '新規登録',
  mockTodayLabel: 'モック今日',
  modeNew: '新規',
  modeEdit: '編集',
  password: 'パスワード',
  visitCountPrefix: '実習日数（カレンダー選択）: ',
  daySuffix: ' 日',
  year: '年',
  month: '月',
  dow: ['日', '月', '火', '水', '木', '金', '土'] as const,
  calTitle:
    'クリックで割当編集（未選択日は選択／選択済をダブルクリックで解除）',
  calHint:
    '未選択日をクリックで実習日に追加。選択済をダブルクリックで解除。単クリックで右の割当を編集。',
  save: '保存',
  pwReissuedPrefix: 'パスワードを ',
  pwReissuedSuffix: ' に再発行',
  pwReissue: 'パスワード再発行',
  cbtRetakeAllowed: 'CBT再受験を許可',
  cbtRetakeAllow: 'CBT再受験許可',
  carryPreviewPrefix: 'モック今日の繰り越し見込み: ',
  dayAssignTitle: '日付ごとのシリーズ割当',
  pickVisitDay: '左のカレンダーで実習日を選んでください。',
  removeVisitDay: 'この日を実習から外す',
  noteLabel: 'メモ（見学など）',
  notePlaceholder: '例: 午前見学（アプリなし）',
  seriesSelectHint:
    'シリーズを選択（0本＝アプリなし日可）。1日に複数可。',
  required: '必須',
  optional: '任意',
  procedure: '手技',
  assigned: '割当中',
  add: '追加',
  zeroSeriesBanner:
    'シリーズ0本 → 見学などアプリなし日として扱います。',
  contentTitle: 'コンテンツ管理',
  opsViewOnly:
    '運用権限のため閲覧のみです。編集・公開切替はフル権限のみ。',
  series: 'シリーズ',
  publish: '公開',
  published: '公開中',
  unpublished: '非公開',
  preview: 'プレビュー',
  unpublish: '非公開にする',
  doPublish: '公開する',
  previewPrefix: 'プレビュー: ',
  chapter: 'チャプター ',
  caseCount: ' ・症例 ',
  hasProcedure: ' ・手技あり',
  cbtResults: 'CBT結果',
  exportCsv: 'Excel用CSV書き出し',
  cbtDesc:
    'クリア済みシリーズから構成された素点のみ。合格／不合格ラベルは出しません。',
  score: '素点',
  scope: '範囲',
  perQuestion: '設問別',
  perQuestionDetail: ' の設問別正誤',
  correctWrong: '正誤',
  question: '問題',
  correct: '正',
  wrong: '誤',
  code: 'コード',
  drawnCount: '出題数',
  examScope: '受験範囲',

  // Phase 4: コンテンツエディタ
  units: 'ユニット',
  unitCount: 'ユニット数',
  publishedCount: '公開中',
  openEditor: 'ユニットを編集',
  backToStages: 'シリーズ一覧へ戻る',
  newUnit: '＋新規ユニット',
  newUnitTitlePlaceholder: 'ユニットのタイトル',
  create: '作成',
  cancel: 'キャンセル',
  unitTitle: 'タイトル',
  requestLine: '依頼文',
  beats: 'ビート',
  addBeat: 'ビートを追加',
  deleteBeat: '削除',
  deleteBeatConfirm: 'このビートを削除しますか？',
  saveDraft: '下書き保存',
  savedDraft: '下書きを保存しました',
  publishUnit: '公開する',
  publishBlocked: '公開条件を満たしていません:',
  publishedOk: '公開しました',
  preview2: 'プレビュー（学生画面と同じ表示）',
  clue: '手がかり',
  newClue: '＋新規作成',
  clueName: '名前',
  clueSummary: '要約',
  clueNone: '（未選択）',
  xp: 'XP',
  supabaseOnly: 'この機能はSupabaseモードでのみ利用できます',
  loginAgain: '再ログインが必要です',
  loading: '読み込み中…',
  dialogueLines: '会話行',
  speaker: '話者',
  text: '本文',
  addLine: '行を追加',
  removeLine: '削除',
  lectureBody: '本文',
  lectureBridge: 'つなぎ（任意）',
  investigateMode: '調査の種類',
  investigatePurpose: '目的',
  investigateHowTo: '手順',
  investigateInputPrompt: '入力欄のラベル',
  investigateAcceptedAnswers: '正解候補',
  investigateAddAnswer: '候補を追加',
  investigateRequired: '必須（未達成だとユニット未クリア）',
  investigateManners: 'マナー（任意）',
  investigateDemoHint: 'ヒント（任意）',
  resolveRequiredClues: '必要な手がかり',
  resolveSteps: 'ステップ',
  resolveAddStep: 'ステップを追加',
  resolveStepPrompt: '設問',
  resolveChoices: '選択肢',
  resolveAddChoice: '選択肢を追加',
  choiceLabel: 'ラベル',
  choiceCorrect: '正解',
  choiceFeedback: 'フィードバック',
  drillQuestions: '問題',
  drillAddQuestion: '問題を追加',
  pickBeat: '左のリストからビートを選択してください。',
  opsNoForm: '運用権限のため編集フォームは表示されません(プレビューのみ閲覧できます)。',
} as const
